version: '2.1'

services:
  contosoadsweb:
    image: contosoadsweb:dev
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    volumes:
      - .\ContosoAdsWeb:C:\inetpub\wwwroot
      - ~\msvsmon:C:\msvsmon:ro
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=windows"

  contosoadswebjob:
    image: contosoadswebjob:dev
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    volumes:
      - .\ContosoAdsWebJob:C:\app
      - ~\msvsmon:C:\msvsmon:ro
    entrypoint: powershell -Command [System.Threading.Thread]::Sleep([System.Threading.Timeout]::Infinite)
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=windows"
